// Code generated by mockery v2.46.3. DO NOT EDIT.
//
// To regenerate:
//
//go:generate mockery --name BookingRepository --dir ../domain --output . --outpkg usecase --filename mock_repo_gen_test.go --with-expecter
//
// NOTE: mockery v2.49 fails on Go 1.26 with "package database/sql/driver without
// types" when loading the domain package (its TimeOfDay Scanner). Until a mockery
// release that supports Go 1.26 is available, the outbox methods (SetPaymentAndStatus
// signature change, CancelWithEvent, FetchUnsentOutbox, MarkOutboxSent) and the
// ConfirmPayment signature change below were edited by hand following the same pattern.

package usecase

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/tienlao/agregator/services/booking-service/internal/domain"
)

// MockBookingRepository is an autogenerated mock type for the BookingRepository interface
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

func (_m *MockBookingRepository) Create(ctx context.Context, b *domain.Booking) error {
	ret := _m.Called(ctx, b)
	return ret.Error(0)
}

type MockBookingRepository_Create_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) Create(ctx, b interface{}) *MockBookingRepository_Create_Call {
	return &MockBookingRepository_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *MockBookingRepository_Create_Call) Return(_a0 error) *MockBookingRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingRepository_Create_Call) Run(fn func(ctx context.Context, b *domain.Booking)) *MockBookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		fn(args[0].(context.Context), args[1].(*domain.Booking))
	})
	return _c
}

func (_m *MockBookingRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	return ret.Error(0)
}

type MockBookingRepository_Delete_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) Delete(ctx, id interface{}) *MockBookingRepository_Delete_Call {
	return &MockBookingRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBookingRepository_Delete_Call) Return(_a0 error) *MockBookingRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_m *MockBookingRepository) GetByID(ctx context.Context, id string) (*domain.Booking, error) {
	ret := _m.Called(ctx, id)
	var r0 *domain.Booking
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}
	return r0, ret.Error(1)
}

type MockBookingRepository_GetByID_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) GetByID(ctx, id interface{}) *MockBookingRepository_GetByID_Call {
	return &MockBookingRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBookingRepository_GetByID_Call) Return(_a0 *domain.Booking, _a1 error) *MockBookingRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_m *MockBookingRepository) GetByIDs(ctx context.Context, ids []string) ([]*domain.Booking, error) {
	ret := _m.Called(ctx, ids)
	var r0 []*domain.Booking
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*domain.Booking); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Booking)
		}
	}
	return r0, ret.Error(1)
}

type MockBookingRepository_GetByIDs_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) GetByIDs(ctx, ids interface{}) *MockBookingRepository_GetByIDs_Call {
	return &MockBookingRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockBookingRepository_GetByIDs_Call) Return(_a0 []*domain.Booking, _a1 error) *MockBookingRepository_GetByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_m *MockBookingRepository) ListByUser(ctx context.Context, userID, status string, offset, limit int) ([]*domain.Booking, int, error) {
	ret := _m.Called(ctx, userID, status, offset, limit)
	var r0 []*domain.Booking
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*domain.Booking); ok {
		r0 = rf(ctx, userID, status, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Booking)
		}
	}
	return r0, ret.Int(1), ret.Error(2)
}

type MockBookingRepository_ListByUser_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) ListByUser(ctx, userID, status, offset, limit interface{}) *MockBookingRepository_ListByUser_Call {
	return &MockBookingRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, status, offset, limit)}
}

func (_c *MockBookingRepository_ListByUser_Call) Return(_a0 []*domain.Booking, _a1 int, _a2 error) *MockBookingRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_m *MockBookingRepository) ListByVenue(ctx context.Context, venueID, status, date, dateFrom, dateTo, cursor string, limit int) ([]*domain.Booking, int, string, error) {
	ret := _m.Called(ctx, venueID, status, date, dateFrom, dateTo, cursor, limit)
	var r0 []*domain.Booking
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, int) []*domain.Booking); ok {
		r0 = rf(ctx, venueID, status, date, dateFrom, dateTo, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Booking)
		}
	}
	return r0, ret.Int(1), ret.String(2), ret.Error(3)
}

type MockBookingRepository_ListByVenue_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) ListByVenue(ctx, venueID, status, date, dateFrom, dateTo, cursor, limit interface{}) *MockBookingRepository_ListByVenue_Call {
	return &MockBookingRepository_ListByVenue_Call{Call: _e.mock.On("ListByVenue", ctx, venueID, status, date, dateFrom, dateTo, cursor, limit)}
}

func (_c *MockBookingRepository_ListByVenue_Call) Return(_a0 []*domain.Booking, _a1 int, _a2 string, _a3 error) *MockBookingRepository_ListByVenue_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_m *MockBookingRepository) UpdateStatus(ctx context.Context, id, status string) error {
	ret := _m.Called(ctx, id, status)
	return ret.Error(0)
}

type MockBookingRepository_UpdateStatus_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) UpdateStatus(ctx, id, status interface{}) *MockBookingRepository_UpdateStatus_Call {
	return &MockBookingRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockBookingRepository_UpdateStatus_Call) Return(_a0 error) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_m *MockBookingRepository) SetPaymentID(ctx context.Context, bookingID, paymentID string) error {
	ret := _m.Called(ctx, bookingID, paymentID)
	return ret.Error(0)
}

type MockBookingRepository_SetPaymentID_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) SetPaymentID(ctx, bookingID, paymentID interface{}) *MockBookingRepository_SetPaymentID_Call {
	return &MockBookingRepository_SetPaymentID_Call{Call: _e.mock.On("SetPaymentID", ctx, bookingID, paymentID)}
}

func (_c *MockBookingRepository_SetPaymentID_Call) Return(_a0 error) *MockBookingRepository_SetPaymentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_m *MockBookingRepository) SetPaymentAndStatus(ctx context.Context, bookingID, paymentID, paymentURL, status string, ev domain.OutboxEvent) error {
	ret := _m.Called(ctx, bookingID, paymentID, paymentURL, status, ev)
	return ret.Error(0)
}

type MockBookingRepository_SetPaymentAndStatus_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) SetPaymentAndStatus(ctx, bookingID, paymentID, paymentURL, status, ev interface{}) *MockBookingRepository_SetPaymentAndStatus_Call {
	return &MockBookingRepository_SetPaymentAndStatus_Call{Call: _e.mock.On("SetPaymentAndStatus", ctx, bookingID, paymentID, paymentURL, status, ev)}
}

func (_c *MockBookingRepository_SetPaymentAndStatus_Call) Return(_a0 error) *MockBookingRepository_SetPaymentAndStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_m *MockBookingRepository) ConfirmPayment(ctx context.Context, bookingID, paymentID, subject string) (*domain.Booking, bool, error) {
	ret := _m.Called(ctx, bookingID, paymentID, subject)
	var r0 *domain.Booking
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.Booking); ok {
		r0 = rf(ctx, bookingID, paymentID, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}
	return r0, ret.Bool(1), ret.Error(2)
}

type MockBookingRepository_ConfirmPayment_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) ConfirmPayment(ctx, bookingID, paymentID, subject interface{}) *MockBookingRepository_ConfirmPayment_Call {
	return &MockBookingRepository_ConfirmPayment_Call{Call: _e.mock.On("ConfirmPayment", ctx, bookingID, paymentID, subject)}
}

func (_c *MockBookingRepository_ConfirmPayment_Call) Return(_a0 *domain.Booking, _a1 bool, _a2 error) *MockBookingRepository_ConfirmPayment_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_m *MockBookingRepository) HasCompleted(ctx context.Context, userID, venueID string) (bool, error) {
	ret := _m.Called(ctx, userID, venueID)
	return ret.Bool(0), ret.Error(1)
}

type MockBookingRepository_HasCompleted_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) HasCompleted(ctx, userID, venueID interface{}) *MockBookingRepository_HasCompleted_Call {
	return &MockBookingRepository_HasCompleted_Call{Call: _e.mock.On("HasCompleted", ctx, userID, venueID)}
}

func (_c *MockBookingRepository_HasCompleted_Call) Return(_a0 bool, _a1 error) *MockBookingRepository_HasCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_m *MockBookingRepository) AutoCompleteVisitEnded(ctx context.Context, visitTimeZone string) ([]domain.BookingCompletedRef, error) {
	ret := _m.Called(ctx, visitTimeZone)
	var r0 []domain.BookingCompletedRef
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.BookingCompletedRef); ok {
		r0 = rf(ctx, visitTimeZone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BookingCompletedRef)
		}
	}
	return r0, ret.Error(1)
}

type MockBookingRepository_AutoCompleteVisitEnded_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) AutoCompleteVisitEnded(ctx, visitTimeZone interface{}) *MockBookingRepository_AutoCompleteVisitEnded_Call {
	return &MockBookingRepository_AutoCompleteVisitEnded_Call{Call: _e.mock.On("AutoCompleteVisitEnded", ctx, visitTimeZone)}
}

func (_c *MockBookingRepository_AutoCompleteVisitEnded_Call) Return(_a0 []domain.BookingCompletedRef, _a1 error) *MockBookingRepository_AutoCompleteVisitEnded_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_m *MockBookingRepository) MarkCompletedEventSent(ctx context.Context, bookingID string) error {
	ret := _m.Called(ctx, bookingID)
	return ret.Error(0)
}

type MockBookingRepository_MarkCompletedEventSent_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) MarkCompletedEventSent(ctx, bookingID interface{}) *MockBookingRepository_MarkCompletedEventSent_Call {
	return &MockBookingRepository_MarkCompletedEventSent_Call{Call: _e.mock.On("MarkCompletedEventSent", ctx, bookingID)}
}

func (_c *MockBookingRepository_MarkCompletedEventSent_Call) Return(_a0 error) *MockBookingRepository_MarkCompletedEventSent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_m *MockBookingRepository) FindUnpublishedCompleted(ctx context.Context, limit int) ([]domain.BookingCompletedRef, error) {
	ret := _m.Called(ctx, limit)
	var r0 []domain.BookingCompletedRef
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.BookingCompletedRef); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BookingCompletedRef)
		}
	}
	return r0, ret.Error(1)
}

type MockBookingRepository_FindUnpublishedCompleted_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) FindUnpublishedCompleted(ctx, limit interface{}) *MockBookingRepository_FindUnpublishedCompleted_Call {
	return &MockBookingRepository_FindUnpublishedCompleted_Call{Call: _e.mock.On("FindUnpublishedCompleted", ctx, limit)}
}

func (_c *MockBookingRepository_FindUnpublishedCompleted_Call) Return(_a0 []domain.BookingCompletedRef, _a1 error) *MockBookingRepository_FindUnpublishedCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_m *MockBookingRepository) CancelWithEvent(ctx context.Context, id string, ev domain.OutboxEvent) error {
	ret := _m.Called(ctx, id, ev)
	return ret.Error(0)
}

type MockBookingRepository_CancelWithEvent_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) CancelWithEvent(ctx, id, ev interface{}) *MockBookingRepository_CancelWithEvent_Call {
	return &MockBookingRepository_CancelWithEvent_Call{Call: _e.mock.On("CancelWithEvent", ctx, id, ev)}
}

func (_c *MockBookingRepository_CancelWithEvent_Call) Return(_a0 error) *MockBookingRepository_CancelWithEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingRepository_CancelWithEvent_Call) Run(fn func(ctx context.Context, id string, ev domain.OutboxEvent)) *MockBookingRepository_CancelWithEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		fn(args[0].(context.Context), args[1].(string), args[2].(domain.OutboxEvent))
	})
	return _c
}

func (_m *MockBookingRepository) FetchUnsentOutbox(ctx context.Context, limit int) ([]domain.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)
	var r0 []domain.OutboxEvent
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OutboxEvent)
		}
	}
	return r0, ret.Error(1)
}

type MockBookingRepository_FetchUnsentOutbox_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) FetchUnsentOutbox(ctx, limit interface{}) *MockBookingRepository_FetchUnsentOutbox_Call {
	return &MockBookingRepository_FetchUnsentOutbox_Call{Call: _e.mock.On("FetchUnsentOutbox", ctx, limit)}
}

func (_c *MockBookingRepository_FetchUnsentOutbox_Call) Return(_a0 []domain.OutboxEvent, _a1 error) *MockBookingRepository_FetchUnsentOutbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_m *MockBookingRepository) MarkOutboxSent(ctx context.Context, ids []int64) error {
	ret := _m.Called(ctx, ids)
	return ret.Error(0)
}

type MockBookingRepository_MarkOutboxSent_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) MarkOutboxSent(ctx, ids interface{}) *MockBookingRepository_MarkOutboxSent_Call {
	return &MockBookingRepository_MarkOutboxSent_Call{Call: _e.mock.On("MarkOutboxSent", ctx, ids)}
}

func (_c *MockBookingRepository_MarkOutboxSent_Call) Return(_a0 error) *MockBookingRepository_MarkOutboxSent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_m *MockBookingRepository) DeleteOrphanPending(ctx context.Context, olderThanMinutes int) (int64, error) {
	ret := _m.Called(ctx, olderThanMinutes)
	return ret.Get(0).(int64), ret.Error(1)
}

type MockBookingRepository_DeleteOrphanPending_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) DeleteOrphanPending(ctx, olderThanMinutes interface{}) *MockBookingRepository_DeleteOrphanPending_Call {
	return &MockBookingRepository_DeleteOrphanPending_Call{Call: _e.mock.On("DeleteOrphanPending", ctx, olderThanMinutes)}
}

func (_c *MockBookingRepository_DeleteOrphanPending_Call) Return(_a0 int64, _a1 error) *MockBookingRepository_DeleteOrphanPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_m *MockBookingRepository) ListBookingStaffNotes(ctx context.Context, bookingID string) ([]domain.BookingStaffNote, error) {
	ret := _m.Called(ctx, bookingID)
	var r0 []domain.BookingStaffNote
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.BookingStaffNote); ok {
		r0 = rf(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BookingStaffNote)
		}
	}
	return r0, ret.Error(1)
}

type MockBookingRepository_ListBookingStaffNotes_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) ListBookingStaffNotes(ctx, bookingID interface{}) *MockBookingRepository_ListBookingStaffNotes_Call {
	return &MockBookingRepository_ListBookingStaffNotes_Call{Call: _e.mock.On("ListBookingStaffNotes", ctx, bookingID)}
}

func (_c *MockBookingRepository_ListBookingStaffNotes_Call) Return(_a0 []domain.BookingStaffNote, _a1 error) *MockBookingRepository_ListBookingStaffNotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_m *MockBookingRepository) AddBookingStaffNote(ctx context.Context, n *domain.BookingStaffNote) error {
	ret := _m.Called(ctx, n)
	return ret.Error(0)
}

type MockBookingRepository_AddBookingStaffNote_Call struct{ *mock.Call }

func (_e *MockBookingRepository_Expecter) AddBookingStaffNote(ctx, n interface{}) *MockBookingRepository_AddBookingStaffNote_Call {
	return &MockBookingRepository_AddBookingStaffNote_Call{Call: _e.mock.On("AddBookingStaffNote", ctx, n)}
}

func (_c *MockBookingRepository_AddBookingStaffNote_Call) Return(_a0 error) *MockBookingRepository_AddBookingStaffNote_Call {
	_c.Call.Return(_a0)
	return _c
}

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
