#!/usr/bin/env bash
# Cloudflare Tunnel setup для фестивального демо banyaorganica.ru.
#
# Что делает:
#   1. Ставит cloudflared (через brew, если нет).
#   2. Логинит тебя в Cloudflare (откроет браузер — ОДИН клик от тебя).
#   3. Создаёт туннель banyaorganica-demo и привязывает к нему два hostname:
#        app.banyaorganica.ru → localhost:3000   (frontend)
#        api.banyaorganica.ru → localhost:8080   (api-gateway)
#   4. Кладёт config рядом со скриптом.
#
# После скрипта запусти туннель:
#   cloudflared tunnel --config deploy/tunnel/config.yml run
#
# Снести всё:
#   cloudflared tunnel route dns --overwrite-dns banyaorganica-demo app.banyaorganica.ru
#   cloudflared tunnel delete banyaorganica-demo

set -euo pipefail

TUNNEL_NAME="banyaorganica-demo"
CONFIG_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="${CONFIG_DIR}/config.yml"

echo "==> 1/4  Проверяю cloudflared"
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "    cloudflared не найден — ставлю через brew"
  brew install cloudflared
else
  echo "    ok: $(cloudflared --version)"
fi

echo "==> 2/4  Логин в Cloudflare (откроется браузер, выбери зону banyaorganica.ru)"
# cloudflared tunnel login идемпотентен: если cert.pem уже есть, ничего не делает.
if [ ! -f "${HOME}/.cloudflared/cert.pem" ]; then
  cloudflared tunnel login
else
  echo "    cert.pem уже есть — пропускаю"
fi

echo "==> 3/4  Создаю туннель ${TUNNEL_NAME}"
if cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "${TUNNEL_NAME}"; then
  echo "    туннель уже существует"
else
  cloudflared tunnel create "${TUNNEL_NAME}"
fi

TUNNEL_ID="$(cloudflared tunnel list | awk -v n="${TUNNEL_NAME}" '$2==n{print $1}')"
if [ -z "${TUNNEL_ID}" ]; then
  echo "ERROR: не смог получить ID туннеля" >&2
  exit 1
fi
echo "    tunnel id = ${TUNNEL_ID}"

echo "==> 4/4  Прописываю DNS-маршруты app.* и api.*"
cloudflared tunnel route dns --overwrite-dns "${TUNNEL_NAME}" "app.banyaorganica.ru"
cloudflared tunnel route dns --overwrite-dns "${TUNNEL_NAME}" "api.banyaorganica.ru"

cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by deploy/tunnel/setup.sh — переезжать на сервер? переделай.
tunnel: ${TUNNEL_ID}
credentials-file: ${HOME}/.cloudflared/${TUNNEL_ID}.json

ingress:
  - hostname: app.banyaorganica.ru
    service: http://localhost:3000
  - hostname: api.banyaorganica.ru
    service: http://localhost:8080
  - service: http_status:404
EOF
echo "    конфиг записан в ${CONFIG_FILE}"

cat <<'EOF'

==================================================================
ГОТОВО. Чтобы поднять туннель:

  cloudflared tunnel --config deploy/tunnel/config.yml run

Запускать каждый день фестиваля. Stop — Ctrl+C.

Перед запуском убедись:
  1. Бэкенд + фронт подняты на localhost (см. deploy/tunnel/BOOT.md)
  2. В Google Cloud Console добавлен redirect URI:
       https://api.banyaorganica.ru/api/v1/auth/google/callback
==================================================================
EOF
