// Command apierrorgen builds api-gateway HTTP error catalog Go code from errors.yaml.
package main

import (
	"bytes"
	"flag"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"
	"unicode"

	"gopkg.in/yaml.v3"
)

type yamlRoot struct {
	Version int        `yaml:"version"`
	Errors  []yamlErr  `yaml:"errors"`
}

type yamlErr struct {
	HTTPStatus int    `yaml:"http_status"`
	Code       string `yaml:"code"`
	Message    string `yaml:"message"`
}

type genErr struct {
	GoName  string
	HTTP    int
	Code    string
	Message string
}

func main() {
	yamlPath := flag.String("yaml", "errors.yaml", "path to errors YAML")
	outPath := flag.String("out", "catalog_gen.go", "path to generated Go file")
	flag.Parse()

	raw, err := os.ReadFile(*yamlPath)
	if err != nil {
		log.Fatal(err)
	}
	var root yamlRoot
	if err := yaml.Unmarshal(raw, &root); err != nil {
		log.Fatal(err)
	}
	if root.Version != 1 {
		log.Fatalf("unsupported catalog version: %d", root.Version)
	}
	seen := make(map[string]struct{})
	var defs []genErr
	for i, e := range root.Errors {
		e.Code = strings.TrimSpace(e.Code)
		e.Message = strings.TrimSpace(e.Message)
		if e.Code == "" || e.Message == "" {
			log.Fatalf("errors[%d]: code and message required", i)
		}
		if e.HTTPStatus < 100 || e.HTTPStatus > 599 {
			log.Fatalf("errors[%d]: invalid http_status %d", i, e.HTTPStatus)
		}
		if _, ok := seen[e.Code]; ok {
			log.Fatalf("duplicate code: %s", e.Code)
		}
		seen[e.Code] = struct{}{}
		name := codeToGoExportedName(e.Code)
		defs = append(defs, genErr{GoName: name, HTTP: e.HTTPStatus, Code: e.Code, Message: e.Message})
	}

	tpl := template.Must(template.New("catalog").Parse(catalogTemplate))
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, defs); err != nil {
		log.Fatal(err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("gofmt: %v; writing unformatted", err)
		formatted = buf.Bytes()
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %s (%d errors)", *outPath, len(defs))
}

func codeToGoExportedName(code string) string {
	parts := strings.Split(code, ".")
	var b strings.Builder
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		b.WriteString(segmentToGoName(p))
	}
	if b.Len() == 0 {
		panic("empty name for code: " + code)
	}
	return b.String()
}

// segmentToGoName turns "INVALID_BODY" or "REQUEST" into "InvalidBody" / "Request".
func segmentToGoName(seg string) string {
	seg = strings.ToLower(seg)
	chunks := strings.Split(seg, "_")
	var b strings.Builder
	for _, c := range chunks {
		c = strings.TrimSpace(c)
		if c == "" {
			continue
		}
		r := []rune(c)
		r[0] = unicode.ToUpper(r[0])
		b.WriteString(string(r))
	}
	return b.String()
}

const catalogTemplate = `// Code generated by tools/apierrorgen; DO NOT EDIT.

package apicatalog

import (
	"encoding/json"
	"net/http"
	"strings"
)

// Entry is a stable API error (machine code + human message + HTTP status).
type Entry struct {
	HTTP    int
	Code    string
	Message string
}

// Write sends JSON: {"code":"...","error":"..."} with the catalog HTTP status.
func (e Entry) Write(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(e.HTTP)
	_ = json.NewEncoder(w).Encode(map[string]string{"code": e.Code, "error": e.Message})
}

// WithMessage returns a copy with a non-empty message (e.g. gRPC detail text).
func (e Entry) WithMessage(msg string) Entry {
	msg = strings.TrimSpace(msg)
	if msg == "" {
		return e
	}
	out := e
	out.Message = msg
	return out
}

var (
{{- range . }}
	// {{ .GoName }} — {{ .Code }}
	{{ .GoName }} = Entry{HTTP: {{ .HTTP }}, Code: {{ printf "%q" .Code }}, Message: {{ printf "%q" .Message }}}
{{- end }}
)

// ByCode returns the catalog entry and true if code is known.
func ByCode(code string) (Entry, bool) {
	switch code {
{{- range . }}
	case {{ printf "%q" .Code }}:
		return {{ .GoName }}, true
{{- end }}
	default:
		return Entry{}, false
	}
}

`
