// Code generated by tools/apierrorgen; DO NOT EDIT.

package apicatalog

import (
	"encoding/json"
	"net/http"
	"strings"
)

// Entry is a stable API error (machine code + human message + HTTP status).
type Entry struct {
	HTTP    int
	Code    string
	Message string
}

// Write sends JSON: {"code":"...","error":"..."} with the catalog HTTP status.
func (e Entry) Write(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(e.HTTP)
	_ = json.NewEncoder(w).Encode(map[string]string{"code": e.Code, "error": e.Message})
}

// WithMessage returns a copy with a non-empty message (e.g. gRPC detail text).
func (e Entry) WithMessage(msg string) Entry {
	msg = strings.TrimSpace(msg)
	if msg == "" {
		return e
	}
	out := e
	out.Message = msg
	return out
}

var (
	// GatewayAuthUnauthorized — GATEWAY.AUTH.UNAUTHORIZED
	GatewayAuthUnauthorized = Entry{HTTP: 401, Code: "GATEWAY.AUTH.UNAUTHORIZED", Message: "Требуется авторизация"}
	// GatewayRequestInvalidBody — GATEWAY.REQUEST.INVALID_BODY
	GatewayRequestInvalidBody = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_BODY", Message: "Некорректное тело запроса"}
	// GatewayRequestInvalidJson — GATEWAY.REQUEST.INVALID_JSON
	GatewayRequestInvalidJson = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_JSON", Message: "Некорректный JSON"}
	// GatewayRequestInvalidQuery — GATEWAY.REQUEST.INVALID_QUERY
	GatewayRequestInvalidQuery = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_QUERY", Message: "Некорректные параметры запроса"}
	// GatewayRequestMissingDate — GATEWAY.REQUEST.MISSING_DATE
	GatewayRequestMissingDate = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.MISSING_DATE", Message: "Укажите дату в формате YYYY-MM-DD"}
	// GatewayRequestMissingDateRange — GATEWAY.REQUEST.MISSING_DATE_RANGE
	GatewayRequestMissingDateRange = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.MISSING_DATE_RANGE", Message: "Укажите date_from и date_to в формате YYYY-MM-DD"}
	// GatewayRequestEmailRequired — GATEWAY.REQUEST.EMAIL_REQUIRED
	GatewayRequestEmailRequired = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.EMAIL_REQUIRED", Message: "Укажите email"}
	// GatewayRequestRateLimited — GATEWAY.REQUEST.RATE_LIMITED
	GatewayRequestRateLimited = Entry{HTTP: 429, Code: "GATEWAY.REQUEST.RATE_LIMITED", Message: "Слишком много запросов. Повторите через несколько минут."}
	// GatewayVenueNotFound — GATEWAY.VENUE.NOT_FOUND
	GatewayVenueNotFound = Entry{HTTP: 404, Code: "GATEWAY.VENUE.NOT_FOUND", Message: "Заведение не найдено"}
	// GatewayDependencyUserServiceUnavailable — GATEWAY.DEPENDENCY.USER_SERVICE_UNAVAILABLE
	GatewayDependencyUserServiceUnavailable = Entry{HTTP: 503, Code: "GATEWAY.DEPENDENCY.USER_SERVICE_UNAVAILABLE", Message: "Сервис пользователей недоступен"}
	// GatewayRequestInvalidVenueId — GATEWAY.REQUEST.INVALID_VENUE_ID
	GatewayRequestInvalidVenueId = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_VENUE_ID", Message: "Некорректный идентификатор заведения"}
	// GatewayRequestInvalidHallId — GATEWAY.REQUEST.INVALID_HALL_ID
	GatewayRequestInvalidHallId = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_HALL_ID", Message: "Некорректный идентификатор зала"}
	// GatewayRequestInvalidPhotoId — GATEWAY.REQUEST.INVALID_PHOTO_ID
	GatewayRequestInvalidPhotoId = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_PHOTO_ID", Message: "Некорректный идентификатор фото"}
	// GatewayRequestInvalidMultipart — GATEWAY.REQUEST.INVALID_MULTIPART
	GatewayRequestInvalidMultipart = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_MULTIPART", Message: "Некорректная multipart-форма или файл слишком большой"}
	// GatewayRequestPhotoFieldRequired — GATEWAY.REQUEST.PHOTO_FIELD_REQUIRED
	GatewayRequestPhotoFieldRequired = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.PHOTO_FIELD_REQUIRED", Message: "Поле photo обязательно"}
	// GatewayRequestInvalidFileRead — GATEWAY.REQUEST.INVALID_FILE_READ
	GatewayRequestInvalidFileRead = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_FILE_READ", Message: "Не удалось прочитать файл"}
	// GatewayRequestEmptyFile — GATEWAY.REQUEST.EMPTY_FILE
	GatewayRequestEmptyFile = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.EMPTY_FILE", Message: "Пустой файл"}
	// GatewayRequestInvalidImageType — GATEWAY.REQUEST.INVALID_IMAGE_TYPE
	GatewayRequestInvalidImageType = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.INVALID_IMAGE_TYPE", Message: "Допустимы только JPEG, PNG и WebP"}
	// GatewayMasterNotCreated — GATEWAY.MASTER.NOT_CREATED
	GatewayMasterNotCreated = Entry{HTTP: 400, Code: "GATEWAY.MASTER.NOT_CREATED", Message: "Сначала создайте профиль мастера"}
	// GatewayInternalInvalidMasterId — GATEWAY.INTERNAL.INVALID_MASTER_ID
	GatewayInternalInvalidMasterId = Entry{HTTP: 500, Code: "GATEWAY.INTERNAL.INVALID_MASTER_ID", Message: "Некорректный идентификатор мастера"}
	// GatewayStorageFailed — GATEWAY.STORAGE.FAILED
	GatewayStorageFailed = Entry{HTTP: 500, Code: "GATEWAY.STORAGE.FAILED", Message: "Не удалось сохранить файл"}
	// GatewayBookingTimeFromRequired — GATEWAY.BOOKING.TIME_FROM_REQUIRED
	GatewayBookingTimeFromRequired = Entry{HTTP: 400, Code: "GATEWAY.BOOKING.TIME_FROM_REQUIRED", Message: "Поле time_from обязательно"}
	// GatewayReviewVenueIdRequired — GATEWAY.REVIEW.VENUE_ID_REQUIRED
	GatewayReviewVenueIdRequired = Entry{HTTP: 400, Code: "GATEWAY.REVIEW.VENUE_ID_REQUIRED", Message: "Параметр venue_id обязателен"}
	// GatewayRequestBodyReadFailed — GATEWAY.REQUEST.BODY_READ_FAILED
	GatewayRequestBodyReadFailed = Entry{HTTP: 400, Code: "GATEWAY.REQUEST.BODY_READ_FAILED", Message: "Не удалось прочитать тело запроса"}
	// GatewayRequestMethodNotAllowed — GATEWAY.REQUEST.METHOD_NOT_ALLOWED
	GatewayRequestMethodNotAllowed = Entry{HTTP: 405, Code: "GATEWAY.REQUEST.METHOD_NOT_ALLOWED", Message: "Метод не разрешён"}
	// GatewayAnalyticsInvalidEventName — GATEWAY.ANALYTICS.INVALID_EVENT_NAME
	GatewayAnalyticsInvalidEventName = Entry{HTTP: 400, Code: "GATEWAY.ANALYTICS.INVALID_EVENT_NAME", Message: "Недопустимое имя события"}
	// GatewayAnalyticsPropsInvalidOrTooLarge — GATEWAY.ANALYTICS.PROPS_INVALID_OR_TOO_LARGE
	GatewayAnalyticsPropsInvalidOrTooLarge = Entry{HTTP: 400, Code: "GATEWAY.ANALYTICS.PROPS_INVALID_OR_TOO_LARGE", Message: "Слишком большой или некорректный объект props"}
	// GatewayOauthGoogleNotConfigured — GATEWAY.OAUTH.GOOGLE_NOT_CONFIGURED
	GatewayOauthGoogleNotConfigured = Entry{HTTP: 503, Code: "GATEWAY.OAUTH.GOOGLE_NOT_CONFIGURED", Message: "Вход через Google не настроен"}
	// GatewayOauthVkNotConfigured — GATEWAY.OAUTH.VK_NOT_CONFIGURED
	GatewayOauthVkNotConfigured = Entry{HTTP: 503, Code: "GATEWAY.OAUTH.VK_NOT_CONFIGURED", Message: "Вход через VK не настроен"}
	// GatewayCrmStaffEmailNotRegistered — GATEWAY.CRM.STAFF_EMAIL_NOT_REGISTERED
	GatewayCrmStaffEmailNotRegistered = Entry{HTTP: 422, Code: "GATEWAY.CRM.STAFF_EMAIL_NOT_REGISTERED", Message: "No registered account for this email; the person must sign up first"}
	// GatewayMasterInvalidServices — GATEWAY.MASTER.INVALID_SERVICES
	GatewayMasterInvalidServices = Entry{HTTP: 400, Code: "GATEWAY.MASTER.INVALID_SERVICES", Message: "Некорректный список услуг"}
	// GatewayUpstreamInvalidArgument — GATEWAY.UPSTREAM.INVALID_ARGUMENT
	GatewayUpstreamInvalidArgument = Entry{HTTP: 400, Code: "GATEWAY.UPSTREAM.INVALID_ARGUMENT", Message: "Некорректный запрос"}
	// GatewayUpstreamNotFound — GATEWAY.UPSTREAM.NOT_FOUND
	GatewayUpstreamNotFound = Entry{HTTP: 404, Code: "GATEWAY.UPSTREAM.NOT_FOUND", Message: "Не найдено"}
	// GatewayUpstreamAlreadyExists — GATEWAY.UPSTREAM.ALREADY_EXISTS
	GatewayUpstreamAlreadyExists = Entry{HTTP: 409, Code: "GATEWAY.UPSTREAM.ALREADY_EXISTS", Message: "Конфликт"}
	// GatewayUpstreamUnauthenticated — GATEWAY.UPSTREAM.UNAUTHENTICATED
	GatewayUpstreamUnauthenticated = Entry{HTTP: 401, Code: "GATEWAY.UPSTREAM.UNAUTHENTICATED", Message: "Требуется авторизация"}
	// GatewayUpstreamPermissionDenied — GATEWAY.UPSTREAM.PERMISSION_DENIED
	GatewayUpstreamPermissionDenied = Entry{HTTP: 403, Code: "GATEWAY.UPSTREAM.PERMISSION_DENIED", Message: "Доступ запрещён"}
	// GatewayUpstreamUnavailable — GATEWAY.UPSTREAM.UNAVAILABLE
	GatewayUpstreamUnavailable = Entry{HTTP: 503, Code: "GATEWAY.UPSTREAM.UNAVAILABLE", Message: "Сервис временно недоступен"}
	// GatewayUpstreamFailedPrecondition — GATEWAY.UPSTREAM.FAILED_PRECONDITION
	GatewayUpstreamFailedPrecondition = Entry{HTTP: 409, Code: "GATEWAY.UPSTREAM.FAILED_PRECONDITION", Message: "Условие не выполнено"}
	// GatewayUpstreamInternal — GATEWAY.UPSTREAM.INTERNAL
	GatewayUpstreamInternal = Entry{HTTP: 500, Code: "GATEWAY.UPSTREAM.INTERNAL", Message: "Внутренняя ошибка сервиса"}
	// GatewayUpstreamUnknown — GATEWAY.UPSTREAM.UNKNOWN
	GatewayUpstreamUnknown = Entry{HTTP: 500, Code: "GATEWAY.UPSTREAM.UNKNOWN", Message: "Ошибка сервиса"}
)

// ByCode returns the catalog entry and true if code is known.
func ByCode(code string) (Entry, bool) {
	switch code {
	case "GATEWAY.AUTH.UNAUTHORIZED":
		return GatewayAuthUnauthorized, true
	case "GATEWAY.REQUEST.INVALID_BODY":
		return GatewayRequestInvalidBody, true
	case "GATEWAY.REQUEST.INVALID_JSON":
		return GatewayRequestInvalidJson, true
	case "GATEWAY.REQUEST.INVALID_QUERY":
		return GatewayRequestInvalidQuery, true
	case "GATEWAY.REQUEST.MISSING_DATE":
		return GatewayRequestMissingDate, true
	case "GATEWAY.REQUEST.MISSING_DATE_RANGE":
		return GatewayRequestMissingDateRange, true
	case "GATEWAY.REQUEST.EMAIL_REQUIRED":
		return GatewayRequestEmailRequired, true
	case "GATEWAY.REQUEST.RATE_LIMITED":
		return GatewayRequestRateLimited, true
	case "GATEWAY.VENUE.NOT_FOUND":
		return GatewayVenueNotFound, true
	case "GATEWAY.DEPENDENCY.USER_SERVICE_UNAVAILABLE":
		return GatewayDependencyUserServiceUnavailable, true
	case "GATEWAY.REQUEST.INVALID_VENUE_ID":
		return GatewayRequestInvalidVenueId, true
	case "GATEWAY.REQUEST.INVALID_HALL_ID":
		return GatewayRequestInvalidHallId, true
	case "GATEWAY.REQUEST.INVALID_PHOTO_ID":
		return GatewayRequestInvalidPhotoId, true
	case "GATEWAY.REQUEST.INVALID_MULTIPART":
		return GatewayRequestInvalidMultipart, true
	case "GATEWAY.REQUEST.PHOTO_FIELD_REQUIRED":
		return GatewayRequestPhotoFieldRequired, true
	case "GATEWAY.REQUEST.INVALID_FILE_READ":
		return GatewayRequestInvalidFileRead, true
	case "GATEWAY.REQUEST.EMPTY_FILE":
		return GatewayRequestEmptyFile, true
	case "GATEWAY.REQUEST.INVALID_IMAGE_TYPE":
		return GatewayRequestInvalidImageType, true
	case "GATEWAY.MASTER.NOT_CREATED":
		return GatewayMasterNotCreated, true
	case "GATEWAY.INTERNAL.INVALID_MASTER_ID":
		return GatewayInternalInvalidMasterId, true
	case "GATEWAY.STORAGE.FAILED":
		return GatewayStorageFailed, true
	case "GATEWAY.BOOKING.TIME_FROM_REQUIRED":
		return GatewayBookingTimeFromRequired, true
	case "GATEWAY.REVIEW.VENUE_ID_REQUIRED":
		return GatewayReviewVenueIdRequired, true
	case "GATEWAY.REQUEST.BODY_READ_FAILED":
		return GatewayRequestBodyReadFailed, true
	case "GATEWAY.REQUEST.METHOD_NOT_ALLOWED":
		return GatewayRequestMethodNotAllowed, true
	case "GATEWAY.ANALYTICS.INVALID_EVENT_NAME":
		return GatewayAnalyticsInvalidEventName, true
	case "GATEWAY.ANALYTICS.PROPS_INVALID_OR_TOO_LARGE":
		return GatewayAnalyticsPropsInvalidOrTooLarge, true
	case "GATEWAY.OAUTH.GOOGLE_NOT_CONFIGURED":
		return GatewayOauthGoogleNotConfigured, true
	case "GATEWAY.OAUTH.VK_NOT_CONFIGURED":
		return GatewayOauthVkNotConfigured, true
	case "GATEWAY.CRM.STAFF_EMAIL_NOT_REGISTERED":
		return GatewayCrmStaffEmailNotRegistered, true
	case "GATEWAY.MASTER.INVALID_SERVICES":
		return GatewayMasterInvalidServices, true
	case "GATEWAY.UPSTREAM.INVALID_ARGUMENT":
		return GatewayUpstreamInvalidArgument, true
	case "GATEWAY.UPSTREAM.NOT_FOUND":
		return GatewayUpstreamNotFound, true
	case "GATEWAY.UPSTREAM.ALREADY_EXISTS":
		return GatewayUpstreamAlreadyExists, true
	case "GATEWAY.UPSTREAM.UNAUTHENTICATED":
		return GatewayUpstreamUnauthenticated, true
	case "GATEWAY.UPSTREAM.PERMISSION_DENIED":
		return GatewayUpstreamPermissionDenied, true
	case "GATEWAY.UPSTREAM.UNAVAILABLE":
		return GatewayUpstreamUnavailable, true
	case "GATEWAY.UPSTREAM.FAILED_PRECONDITION":
		return GatewayUpstreamFailedPrecondition, true
	case "GATEWAY.UPSTREAM.INTERNAL":
		return GatewayUpstreamInternal, true
	case "GATEWAY.UPSTREAM.UNKNOWN":
		return GatewayUpstreamUnknown, true
	default:
		return Entry{}, false
	}
}
